//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-updateUserDetailsById-DMOPS_ID_user_details___EN_ga5r31ylxl__updateUserDetailsById
import { updateUserDetailsById as DMOPS_ID_user_details___EN_ga5r31ylxl__updateUserDetailsById } from './dm-services/user_details/user_details/updateUserDetailsById';
//CORE_REFERENCE_IMPORT-updateAllUserDetailss-DMOPS_ID_user_details___EN_ga5r31ylxl__updateAllUserDetailss
import { updateAllUserDetailss as DMOPS_ID_user_details___EN_ga5r31ylxl__updateAllUserDetailss } from './dm-services/user_details/user_details/updateAllUserDetailss';
//CORE_REFERENCE_IMPORT-findUserDetailsById-DMOPS_ID_user_details___EN_ga5r31ylxl__findUserDetailsById
import { findUserDetailsById as DMOPS_ID_user_details___EN_ga5r31ylxl__findUserDetailsById } from './dm-services/user_details/user_details/findUserDetailsById';
//CORE_REFERENCE_IMPORT-findAllUserDetailss-DMOPS_ID_user_details___EN_ga5r31ylxl__findAllUserDetailss
import { findAllUserDetailss as DMOPS_ID_user_details___EN_ga5r31ylxl__findAllUserDetailss } from './dm-services/user_details/user_details/findAllUserDetailss';
//CORE_REFERENCE_IMPORT-deleteUserDetailsById-DMOPS_ID_user_details___EN_ga5r31ylxl__deleteUserDetailsById
import { deleteUserDetailsById as DMOPS_ID_user_details___EN_ga5r31ylxl__deleteUserDetailsById } from './dm-services/user_details/user_details/deleteUserDetailsById';
//CORE_REFERENCE_IMPORT-deleteAllUserDetailss-DMOPS_ID_user_details___EN_ga5r31ylxl__deleteAllUserDetailss
import { deleteAllUserDetailss as DMOPS_ID_user_details___EN_ga5r31ylxl__deleteAllUserDetailss } from './dm-services/user_details/user_details/deleteAllUserDetailss';
//CORE_REFERENCE_IMPORT-createAllUserDetails-DMOPS_ID_user_details___EN_ga5r31ylxl__createAllUserDetails
import { createAllUserDetails as DMOPS_ID_user_details___EN_ga5r31ylxl__createAllUserDetails } from './dm-services/user_details/user_details/createAllUserDetails';
//CORE_REFERENCE_IMPORT-createUserDetails-DMOPS_ID_user_details___EN_ga5r31ylxl__createUserDetails
import { createUserDetails as DMOPS_ID_user_details___EN_ga5r31ylxl__createUserDetails } from './dm-services/user_details/user_details/createUserDetails';

export const DmRoutes = [
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateUserDetailsById-DMOPS_ID_user_details___EN_ga5r31ylxl__updateUserDetailsById
  DMOPS_ID_user_details___EN_ga5r31ylxl__updateUserDetailsById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateAllUserDetailss-DMOPS_ID_user_details___EN_ga5r31ylxl__updateAllUserDetailss
  DMOPS_ID_user_details___EN_ga5r31ylxl__updateAllUserDetailss,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-findUserDetailsById-DMOPS_ID_user_details___EN_ga5r31ylxl__findUserDetailsById
  DMOPS_ID_user_details___EN_ga5r31ylxl__findUserDetailsById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-findAllUserDetailss-DMOPS_ID_user_details___EN_ga5r31ylxl__findAllUserDetailss
  DMOPS_ID_user_details___EN_ga5r31ylxl__findAllUserDetailss,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-deleteUserDetailsById-DMOPS_ID_user_details___EN_ga5r31ylxl__deleteUserDetailsById
  DMOPS_ID_user_details___EN_ga5r31ylxl__deleteUserDetailsById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-deleteAllUserDetailss-DMOPS_ID_user_details___EN_ga5r31ylxl__deleteAllUserDetailss
  DMOPS_ID_user_details___EN_ga5r31ylxl__deleteAllUserDetailss,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-createAllUserDetails-DMOPS_ID_user_details___EN_ga5r31ylxl__createAllUserDetails
  DMOPS_ID_user_details___EN_ga5r31ylxl__createAllUserDetails,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-createUserDetails-DMOPS_ID_user_details___EN_ga5r31ylxl__createUserDetails
  DMOPS_ID_user_details___EN_ga5r31ylxl__createUserDetails,
];
